if !exists('g:vscode')
	source ~/.config/nvim/basic-setting.vim
	source ~/.config/nvim/plugconfig/indentline.vim
	source ~/.config/nvim/plugconfig/vifm.vim
	source ~/.config/nvim/plugconfig/vimwiki.vim
	source ~/.config/nvim/plugconfig/easy-motion.vim
	source ~/.config/nvim/plugconfig/undotree.vim
	source ~/.config/nvim/plugconfig/emmet.vim
	source ~/.config/nvim/plugconfig/table-mode.vim
	source ~/.config/nvim/plugconfig/goyo.vim
	source ~/.config/nvim/plugconfig/git-gutter.vim
	source ~/.config/nvim/plugconfig/vim-airline.vim
	source ~/.config/nvim/plugconfig/vim-hexokinase.vim
	source ~/.config/nvim/plugconfig/vim-fzf.vim
	source ~/.config/nvim/plugconfig/fern.vim
	source ~/.config/nvim/plugconfig/vim-closetag.vim
	source ~/.config/nvim/plugconfig/coc.vim
	source ~/.config/nvim/plugconfig/vim-which-key.vim
endif
