#!/bin/sh
bspc rule -r "*"

###---Autostart---###
nm-applet &
xrdb ~/.Xresources &
picom -b --experimental-backends &
hsetroot -cover ~/.config/wall.png &
flameshot &
fcitx -d &
launchpolybar &

killall bspswallow
pidof bspswallow | bspswallow &

###---MONITORS---###
bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7
bspc monitor DisplayPort-1 -d 8 9
bspc monitor HDMI-A-0 -d 10

###---Global Settings---###
bspc config automatic_scheme alternate
bspc config initial_polarity second_child
bspc config pointer_modifier lock
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config click_to_focus none

bspc config focus_follows_pointer true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config normal_border_color	"#4c566a"
bspc config active_border_color	"#1e1e1e"
bspc config focused_border_color "#327bd1"
bspc config presel_feedback_color	"#327bd1"
bspc config urgent_border_color "#dd2727"

###---Monitor And Desktop Settings----###
bspc config top_padding 32
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config border_width 2
bspc config window_gap 10

###---Rules---###
bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a Screenkey manage=off
bspc rule -a guvcview state=floating rectangle=480x270+1440+810 sticky=on layer=above
